### ISSUE TITLE
[C++] "this" is a keyword

### ISSUE THREAD

**Issue by alekseyt** [EvgeniyPeshkov/syntax-highlighter#14]
`this` as in

```c++
this->f();
```

Currently it's not highlighted. I tried to add it to the end of the list of `control` keywords in `grammar/cpp.json`:

```diff
         "\"catch\"": "control",
+        "\"this\"": "control",
 
         "\"sizeof\"": "operator",
```

but it's still not highlighted. What am i missing?

**Comment by EvgeniyPeshkov** [comment]
Unfortunately, *tree-sitter* parses such expressions like `varibale->function()`. Without expansion of syntax nodes and looking at what text is actually inside, it's impossible to distinguish keywords in such cases. At the moment i do not plan to implement parsing of node's text because of performance impact. This will imply considerable performance drop, because every term will have to be checked against a list of special words or regexps. Please, look at [this answer](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/3#issuecomment-496200952) for details.

**Comment by alekseyt** [comment]
If it's on tree-siiter then i'm closing this issue then.
