### ISSUE TITLE
The highlighter doesn't work

### ISSUE THREAD

**Issue by Fallensouls** [EvgeniyPeshkov/syntax-highlighter#30]
Hello!
I tried to use this extension to highlight my `Go` files on latest VSCode but it didn't work. I followed the guide and set `workbench.colorCustomizations`, there was nothing changed.
![QQ图片20190805130149](https://user-images.githubusercontent.com/40592337/62440118-3aff8800-b781-11e9-934c-c19c319a1189.png)

I have no idea what's wrong, any advice?

**Comment by EvgeniyPeshkov** [comment]
Hello @Fallensouls ,
Is [Go extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) installed in your VSCode?
Without this extension VSCode doesn't recognize .go files (they are treated as *plaintext*) and initialization of {Syntax Highlighter} isn't triggered.

**Comment by Fallensouls** [comment]
@EvgeniyPeshkov Yeah, I am sure the go extension is installed and I use gopls. Actually, the highlighter seems not work when I open .py files, either. (I have also installed the python extension to test it)
If I change `editor.tokenColorCustomizations`, there is something different but obviously not I want.


![QQ图片20190805232843](https://user-images.githubusercontent.com/40592337/62476208-22bb5780-b7d9-11e9-8dba-97064f5ba2dc.png)

Do you have any idea about this? Thx : )

**Comment by EvgeniyPeshkov** [comment]
Hmmm... This is really strange. It's the first time extension doesn't work at all.
Could you please check `syntax.highlightLanguages` in your `settings.json`? Just in case. This is the only setting that can disable Syntax Highlighter.
Also, could you kindly say your OS?

**Comment by Fallensouls** [comment]
I check it and it is default value. I don't know why `workbench.colorCustomizations` can't change color but `editor.tokenColorCustomizations` can, they are using the same analysis tool, right?
I am working on Windows x64.

**Comment by EvgeniyPeshkov** [comment]
`workbench.colorCustomizations` allows to customize UI colors, while `editor.tokenColorCustomizations` defines colors of syntax tokens.
I've embedded color settings of Syntax Highlighter into `workbench.colorCustomizations` simply because VSCode extension API do not provide access to token colors.
It is strange question, but maybe you have VSCode installed on D:\ drive, or your user folder is not on C:\ drive?

**Comment by Fallensouls** [comment]
@EvgeniyPeshkov Yeah, actually I have VSCode installed on D:\ drive. When I reinstall it on C:\ drive, the  highlighter works correctly. Could you please tell me the reason? Thank you very much!

**Comment by EvgeniyPeshkov** [comment]
The reason has a long story (=.
The main cause is [this line](https://github.com/tree-sitter/tree-sitter/blob/ae41a78d3c074e8bb0f05bc96d61c5f3a88b37e6/lib/binding_web/binding.js#L571) in `tree-sitter-web` implementation. Basically, it checks that provided path is absolute, but in a strange way. It assumes that no protocol must be specified. On Windows though absolute paths have form `C:/Users/...`, so `C` is treated as protocol and everything goes wrong. So for Windows I made workaround removing drive letter and using paths of form `/Users/...` when loading parser's wasm. By default such path points to file on C:\ drive. This fix is so ugly, that I haven't even pushed it to the repo. So this worked in general, not many people install VSCode on secondary drives.
Fortunately, [the bug](https://github.com/tree-sitter/tree-sitter/issues/338) is already fixed in [this commit](https://github.com/tree-sitter/tree-sitter/commit/3ec91a8d8a1c83d358a599b83740416cad783a87#diff-c4b7158334648b59cc1569d3fb40efb8). So today I'll publish the new version that will work when VSCode is installed on any drive (=. Thank you very much for discovering this issue.

**Comment by Fallensouls** [comment]
Thanks for your explanation.
Since the new version has fixed the bug, I think we can close the issue.
