### ISSUE TITLE
Overrides Rainbow Brackets

### ISSUE THREAD

**Issue by ganzuul** [EvgeniyPeshkov/syntax-highlighter#50]
Rainbow Brackets by 2gua colors pairs of e.g. parenthesis, which helps immensely with finding errors in nesting. And it looks pretty. When Syntax Highlighter is enabled it seems to override the stylesheet for brackets, clobbering the entire purpose of the other extension.

This happens with C/C++ but not with Python code, with and without Microsoft's C/C++ extension. 

Removing 
```        
        "\";\"": "punctuation",
        "\":\"": "punctuation",
        "\",\"": "punctuation",
        "\"[\"": "punctuation",
        "\"]\"": "punctuation",
        "\"{\"": "punctuation",
        "\"}\"": "punctuation",
        "\"(\"": "punctuation",
        "\")\"": "punctuation"
```

from grammars/cpp.json seems to fix the problem.

**Comment by EvgeniyPeshkov** [comment]
Hello @ganzuul ,
This happens because both extensions use decoration API. And priority of decoration providers (order in which decorations are applied) cannot be defined.
I recommend you to simply disable highlighting of punctuation tokens. There is [special setting](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/README.md#syntaxhighlightterms) for this. Just put `"syntax.highlightTerms": [...],` in your `settings.json` and remove `"punctuation"` from the array of terms to highlight.
